### PR TITLE
Hazelcast patch

### PR DESCRIPTION
**Pull request by vincer**

### CODE REVIEW

**Comment by glinscott** [comment]
LGTM

**Comment by marczych** [comment]
Awesome!

The plan was to ditch this repo and go back to the public "releases" on the next major update. Is this patch also in the upstream or will we have to continue to merge the upstream here?

**Comment by vincer** [comment]
I heartily support getting rid of this repo, but sadly this is not upstream. Its more of a quick patch and ignores the root cause. That said, we could still try submitting it as a PR to them since it does avoid that ridiculous bug.

**Comment by marczych** [comment]
Yeah, that'd be great. They might not be crazy about swallowing the error and pretending like it's a cache miss but I think that it's much better than spewing megabytes of garbage to the terminal. @glinscott I remember you posting this patch somewhere (maybe bazel-discuss?) - was it well received or should we not even bother opening a PR?

Also, the contributing guidelines are a bit daunting: https://www.bazel.io/contributing.html

**Comment by glinscott** [comment]
It's more of a hack than a real patch, so unlikely to make it into master.  Plus they are rewriting the caching implementation to use grpc as well, so this codepath is probably going to go away.

**Pull request merged**
